# Generated by Django 2.2.3 on 2019-07-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='name',
            new_name='gender_name',
        ),
    ]
