# Generated by Django 2.2 on 2019-07-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genders', '0002_auto_20190714_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
